### ISSUE TITLE
README

### ISSUE THREAD

**Issue by RichardLitt** [libp2p/js-libp2p-record#2]
Hey @diasdavid - can you explain to me what is stopping you from having super-sweet generated READMEs? What do you want?

**Comment by diasdavid** [comment]
I will only worry about the readme, once there is something to show, otherwise what is the purpose of documenting a placeholder?

**Comment by dignifiedquire** [comment]
Will be filled in with #1

**Comment by diasdavid** [comment]
Do note that the README that you see is literally what gh creates by default when I say "I want a README". Maybe you could reach out to Github to ask them if standard-readme can be a thing that they offer as an option?

**Comment by RichardLitt** [comment]
> I will only worry about the readme, once there is something to show, otherwise what is the purpose of documenting a placeholder?

If there is no documentation, than the state for this repo is entirely in your head. This precludes others being able to work on it, and means that you need to keep this state in mind. This is fine if you want to do it locally - but on the organization, this quickly leads to friction, as others can't guess what you were getting at when you made this. Ideally, organizational work should always be readily accessible to someone else in the org, or you're creating barriers to entry. If you want to make stub repos, taking a couple of seconds to explain what it is and why - perhaps linking to the tracking issue for your efforts - goes a long way towards being kinder to other people in the org. If there is some sort of process issue - for instance, you don't know what a README should look like - let me know. I can help with that, which is what I was trying to get to above. 

> Maybe you could reach out to Github to ask them if standard-readme can be a thing that they offer as an option?

GitHub is notoriously bad at dealing with requests from developers. :/

**Comment by diasdavid** [comment]
Understood. Thank you for clarifying the value, would be interesting to correlate it with time investment and the about of 'engagement misses' for a module that doesn't exist. 

Until a couple of weeks ago, this module was: https://github.com/ipfs/specs/tree/master/iprs-interplanetary-record-system, now it is https://github.com/libp2p/go-libp2p-record

**Comment by RichardLitt** [comment]
> would be interesting to correlate it with time investment and the number of 'engagement misses' for a module that doesn't exist.

This would be difficult. By it's nature, these sort of interactions are hidden; you won't be able to easily track them without having insight into GitHub's analytics. I view it as something akin to politeness; by labelling what we're doing, a bit above minimally, we're able to work together a bit easier.
